### ISSUE TITLE
Atpacks and Devices can not choose

### ISSUE THREAD

**Issue by ghost** [BsAtHome/atpack#1]
Hello,
I now download your atpack, but Atpacks and Devices can not choose. Both are -
I tested your online test http://media.vagrearg.org/atpack/ and work only this online test.
I use Chrome, Edge and Internet Explorer, without a change.
Can you help me?

In browser console are errors:
Uncaught SyntaxError: Unexpected number
atpackrun.js:51 Uncaught ReferenceError: $ is not defined
    at atpackrun.js:51

**Comment by BsAtHome** [comment]
How did you install it? Which OS?
Is the jquery.js properly symlinked to the actual file and it has the correct permissions?
Did you fix atpackbase.js to point to the right files if you changed anything in the paths?
Have you tried to enable the JS debugger and see the console output?

**Comment by ghost** [comment]
I only download zip from this github website. Unpack and open atpack.html.
OS: Win 10

**Comment by BsAtHome** [comment]
I suspect that the jquery symlink fails or a permissions problem. Please check if the browser can and does read all static script-files and that your browser/OS is configured to execute scripts on your local computer.

**Comment by ghost** [comment]
I add all persmissions to all files. Scripts works only from your test website. My browser read all static script files without problems. How I can symlink jquery with this html?

**Comment by BsAtHome** [comment]
You can simply forego the symlink and change the reference to jquery in the atpack.html file to the actual jquery-3.3.1.min.js file.

**Comment by ghost** [comment]
This is really helpful. Thank you very much. Now it works.
