### ISSUE TITLE
CORS policy blocking access to xml files

### ISSUE THREAD

**Issue by valerionew** [BsAtHome/atpack#2]
I linked the correct jquery file in atpack.html and now i get 
```
jquery-3.3.1.min.js:2 Access to XMLHttpRequest at 'file:///C:/*/atpack-master/Atmel.ATmega_DFP.atpack/Atmel.ATmega_DFP.pdsc' from origin 'null' has been blocked by CORS policy: 
Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.  
```
```
jquery-3.3.1.min.js:2 Access to XMLHttpRequest at 'file:///C:/*/atpack-master/Atmel.ATtiny_DFP.atpack/Atmel.ATtiny_DFP.pdsc' from origin 'null' has been blocked by CORS policy: 
Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.```

**Comment by BsAtHome** [comment]
You must give more information than the error message. The message says nothing without the proper context within it is generated. At least you must give the following info:
- Which browser and OS?
- What did you change in the files?
- Which URL are you using in the browser?
- Have you tried other browsers?
- Other relevant information on what you do/did

From that we can start an analysis.

**Comment by valerionew** [comment]
Yessir, sorry for the lack of details.
The error is presented when the page is opened, the first dropdown list does say "Select a pack" but has no options in it.
My test refers to chrome 71.0.3578.80 on windows 10 home 1803 build 17134.407.
I've tested also internet explorer, which doesn't work at all, and on Microsoft Edge, where i can select both a pack and a device but i can't get any data showing.

The only thing i've changed is from `jquery.js` to `jquery-3.3.1.min.js` [on this line of atpack.html](https://github.com/BsAtHome/atpack/blob/0f8c0fb8a45b490223536fe69a1fb77e1418c796/atpack.html#L22), as suggested in #1, since i was getting this error at first:
```
Uncaught SyntaxError: Unexpected number
atpackrun.js:51 Uncaught ReferenceError: $ is not defined
    at atpackrun.js:51
```

I've tried putting it online on a server running apache and it works fine, probably because it's using http so the CORS policy does not apply.

**Comment by BsAtHome** [comment]
So, Chrome has a CORS problem. Edge seems to have a Javascript or DOM issue.

CORS is only a problem depending on the protocol. It usually should not trigger on the file:// protocol. How can the file:// protocol become cross-domain... That may mean that you are not typing the correct primary URL and Chrome is adding the missing parts, triggering the error.
What is the complete and exact URL you are using to get to the atpack main page?
If you activate the Chrome debugger (ctrl-shift-i IIRC). Then goto the network tab and do a full reload and track the request(s). This may explain how Chrome determines to become cross-domain.

While you are at it. What is Edge complaining about?

**Comment by valerionew** [comment]
The full path is; `file:///C:/Users/valer/Downloads/atpack-master/atpack.html`. 

This is a screen of the network tab and the errors
![image](https://user-images.githubusercontent.com/17505995/49899270-887a5e00-fe5b-11e8-80f5-ef79ec9d40ab.png)

Edge doesn't display any particular error, it only shows two warnings:
`HTML1527: DOCTYPE expected. Consider adding a valid HTML5 doctype: "<!DOCTYPE html>"`
`CONSOLE21301: serviceWorker.getRegistrations is rejected due to unsecure context or host restriction in file:///C:/Users/valer/Downloads/atpack-master/atpack.html.`

**Comment by BsAtHome** [comment]
After some searching: The default policy on chrome/chromium is not to allow the file: protocol to load local files.

You can bypass this policy by starting the browser with the --allow-file-access-from-files option (f.ex. start the browser from the command line and add the option).

This cannot be fixed by other means because there is no server involved in the file: protocol. Therefore, no CORS headers can be provided to solve the problem. The real problem is that CORS on the file: protocol only makes sense on directories outside the base-path of the file and script running. Atpack only runs in a sub-hierarchy of the base-path. However, the designers/developers seem to be of other opinion.

Edge complains about context restrictions. That may be CORS related, but may also be file-access rules on the windows filesystem. I have no windows, so I cannot get further into that problem.

**Comment by valerionew** [comment]
Yep, thanks, `-–allow-file-access-from-files` works.  
Is it worth adding this info to the readme?  
(all chrome instances have to be closed first)
